"""Settings

Revision ID: 2f1485fbd784
Revises: 15bc4d6460be
Create Date: 2026-05-01 14:04:07.706929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f1485fbd784'
down_revision: Union[str, Sequence[str], None] = '15bc4d6460be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user_settings',
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('locale', sa.String(length=8), nullable=True),
        sa.Column('upcoming_class_notifications_enabled', sa.Boolean(), nullable=False),
        sa.Column('daily_class_notifications_enabled', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('user_id')
    )

    op.execute("""
        INSERT INTO user_settings (user_id, locale, upcoming_class_notifications_enabled, daily_class_notifications_enabled, created_at)
        SELECT id, locale, FALSE, FALSE, NOW()
        FROM users
        ON CONFLICT DO NOTHING
    """)

    op.drop_column('users', 'locale')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('locale', sa.VARCHAR(length=8), autoincrement=False, nullable=True))

    op.execute("""
        UPDATE users
        SET locale = user_settings.locale
        FROM user_settings
        WHERE users.id = user_settings.user_id
    """)

    op.drop_table('user_settings')
    # ### end Alembic commands ###
